package com.wk.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private String sessionId;
    private String name;
    private String age;
    private Long id;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(String sessionId, String name, String age, Long id) {
        this.sessionId = sessionId;
        this.name = name;
        this.age = age;
        this.id = id;
    }

    public User(String sessionId, String name, String age) {
        this.sessionId = sessionId;
        this.name = name;
        this.age = age;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
